
export enum CsvSchwab {
    SYMBOL,
    DESCRIPTION,
    QUANTITY,
    PRICE,
    MARKET_VALUE,
    DAY_CHANGE_DOLLAR,
    DAY_CHANGE_PERCENT,
    COST_BASIS,
    GAIN_LOSS_DOLLAR,
    GAIN_LOSS_PERCENT,
    REINVEST_DIVIDENDS,
    REINVEST_CAPITAL,
    PERCENT_ACCOUNT,
    DIVIDEND_YIELD,
    EX_DIVIDEND,
    SECURITY_TYPE
}